Se printea el resultado del análisis

diff --git a/2_SCRIPTS/2_just_execute_analysis b/2_SCRIPTS/2_just_execute_analysis
--- a/2_SCRIPTS/2_just_execute_analysis
+++ b/2_SCRIPTS/2_just_execute_analysis
@@ -7,7 +7,7 @@ for f in *; do
 	if [ -d $f ];
 	then
 		cd "$f";
-		Rscript analisis.r > output.txt;
+		Rscript analisis.r > output.txt && echo "/$f done." || echo "/$f failed.";
 		cd ..;
 	fi;
 done;
diff --git a/2_SCRIPTS/3_execute_analisis b/2_SCRIPTS/3_execute_analisis
--- a/2_SCRIPTS/3_execute_analisis
+++ b/2_SCRIPTS/3_execute_analisis
@@ -6,7 +6,7 @@ cd ../3_DATA
 for f in *; do
 	if [ -d $f ];
 	then
-		cp analisis.r "$f"/analisis.r;
+		cp ../1_ANALYSIS/analisis.r "$f"/analisis.r;
 	fi
 done;
 
@@ -15,7 +15,7 @@ for f in *; do
 	if [ -d $f ];
 	then
 		cd "$f";
-		Rscript analisis.r > output.txt;
+		Rscript analisis.r > output.txt && echo "/$f done." || echo "/$f failed";
 		cd ..;
 	fi;
 done;
